# Generated by Django 3.2.4 on 2021-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210630_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_dislike',
            name='like_dislike',
            field=models.BooleanField(null=True),
        ),
    ]
